### ISSUE TITLE
KK cannot delete iris overlay to empty.

### ISSUE THREAD

**Issue by smartluo1833** [ManlyMarco/Illusion-Overlay-Mods#10]
I cannot delete a card's iris overlay to empty.

I click "Clear texture" in "Iris Overlays" → save the card → read the card → The iris overlay appear again.

The card is come from
https://www.pixiv.net/artworks/85192064

I also found
This situation only occurs on this card, whether it is related to the incompatibility of the overlay plugin version(New cannot delete old). 

I use:
HF Patch 3.4
Sideloader Modpack Changelog 1013

**Comment by ManlyMarco** [comment]
This is because this card uses MaterialEditor to set the eye texture as well as iris overlays. After you remove the overlay the ME edit is applied instead. You have to reset the eye texture override in Material Editor to reset the eye to base texture.
