### ISSUE TITLE
Some cards got black skin from the neck down.

### ISSUE THREAD

**Issue by NonsanXX** [ManlyMarco/Illusion-Overlay-Mods#11]
Hello, When I got into game some girls are black from the neck down when I'm not talking to, 
![148400211_442473880285993_1795723706273050691_n](https://user-images.githubusercontent.com/79022982/107860131-3042aa80-6e70-11eb-97f4-16814ba676a3.png)
But when I talk with them they seems to be normal.
![148713954_434036821370414_8414917997834830231_n](https://user-images.githubusercontent.com/79022982/107860138-3769b880-6e70-11eb-9661-067ee2bdfbcc.png)
And when I delete KK_OverlayMods.dll this problem are gone.
Can you help me?
P.S. It's happen to some cards, this is some cards that happens.
![Screenshot 2021-02-14 030006](https://user-images.githubusercontent.com/79022982/107860229-c4147680-6e70-11eb-97f3-ba0f9e291ff9.png)
Sorry for my bad english.

**Comment by ManlyMarco** [comment]
Hello!
This is not an issue with this plugin but with a broken uncensor. Remove the `[KK][Female]Nam_Outlined_Pussy_Pack`  uncensor from your mods folder for now, or download the fixed version from the discord server and update it manually.

**Comment by NonsanXX** [comment]
Thank you, my problem are fixed now.
