### ISSUE TITLE
Unusual Texture, Has to be 2048x2048

### ISSUE THREAD

**Issue by ShinAli21** [ManlyMarco/Illusion-Overlay-Mods#17]
The texture will not work as it says it needs to be 2048x2048 and will give off a warning.

**Comment by ManlyMarco** [comment]
It means that whatever you are trying to use overlay on has ha different texture resolution than your overlay. It will still work but be lower quality or make the card larger than it has to be.

**Comment by ShinAli21** [comment]
Ah. I see I was using the Body UV to help me with the textures, but it was refusing to work and gave off that warning I mentoin.
