### ISSUE TITLE
Does not work with HS2 western face mod by DBLin

### ISSUE THREAD

**Issue by Electrognome** [ManlyMarco/Illusion-Overlay-Mods#18]
Eye overlays does not work with DBLin's Western Face mod for HS2. This head mod uses the same exact eye model with same exact UVs as default heads. Probably IDs issue.

**Comment by ManlyMarco** [comment]
IDs don't matter, this plugin hooks into the game code that generates eye textures so it should work no matter what as long as the game sliders work on the eyes. There must be something different about the model that causes this.
