### ISSUE TITLE
Iris Overlays removed for Wedding and Concert

### ISSUE THREAD

**Issue by OMGitsMatt45** [ManlyMarco/Illusion-Overlay-Mods#19]
So I downloaded a Venti card that came with a custom iris overlay, and when I went to put him into a concert or wedding event, the overlay disappears and I'm left with Venti having blank eyes, which is really creepy.

**Comment by ManlyMarco** [comment]
I could only reproduce the issue in KK Party live mode, fixed it here https://github.com/IllusionMods/BepisPlugins/commit/1f1eeab90f4a0fcec9741c0dff3b5563f5025bb3
Everything seems to work fine in KK. I couldn't reproduce the issue in KK Party wedding mode because it's completely broken anyways.
