### ISSUE TITLE
Breast size regression bug in 6.1.3

### ISSUE THREAD

**Issue by Timo713** [ManlyMarco/Illusion-Overlay-Mods#27]
There is a strange, very specific bug introduced in the latest 6.1.3 version when replacing characters in studio, the conditions are the following:

In studio, characters in slots that are replaced for the first time after loading a scene and DON'T have any body overlays/underlays will not have their breast size values updated on the first load, you need to load them twice to load them correctly.

This only happens once per scene loading session on characters that were already on the scene when it was loaded and not those who get replaced after importing a new character to the scene during that same session.

To replicate this bug, you need to add a character without any body overlays/underlays to the scene first, save the scene, load it, and replace the character with another one with a different breast size that also doesn't have any body overlays/underlays on it.

**Comment by ManlyMarco** [comment]
Are you sure this is something new to specifically 6.1.3? If both characters don't have any overlays then the overlay plugin should do nothing. If it is a new issue in the latest release then I would guess it has to be somehow caused by #26.

**Comment by Timo713** [comment]
Yes, I'm using 6.1.2 for now and all characters load fine.

**Comment by ManlyMarco** [comment]
@takahiro0327 Can you give this a look?

**Comment by takahiro0327** [comment]
@Timo713 
Try this DLL. It should fix it.
It's amazing how you were able to identify Overlay as the cause. How did you do it?

[HS2_OverlayMods.zip](https://github.com/user-attachments/files/15755149/HS2_OverlayMods.zip)
[KK_OverlayMods.zip](https://github.com/user-attachments/files/15755150/KK_OverlayMods.zip)
[KKS_OverlayMods.zip](https://github.com/user-attachments/files/15755151/KKS_OverlayMods.zip)
[AI_OverlayMods.zip](https://github.com/user-attachments/files/15755152/AI_OverlayMods.zip)
[EC_OverlayMods.zip](https://github.com/user-attachments/files/15755153/EC_OverlayMods.zip)

**Comment by Timo713** [comment]
@takahiro0327
Yup, it seems to be fixed now.
As for how I identified the cause, well, just trial and error. I kept disabling chunks of plugins and tested until the bug disappeared and then narrowed the search until this plugin was left, lol.

**Comment by ManlyMarco** [comment]
@Timo713 https://github.com/ManlyMarco/Illusion-Overlay-Mods/releases/tag/v6.1.4
