### ISSUE TITLE
Certain edits not showing on cards when loaded in the Character Creator

### ISSUE THREAD

**Issue by AsuraSeth** [ManlyMarco/Illusion-Overlay-Mods#30]
It all started when I updated this mod(OverlayMods_6.1.3.0) and it's requirements(latest), Suddenly when loading cards(characters) on the Char Creator, Overlays would be seemingly missing, after doing some test I discovered this was just visual and only on the Char Creator, Even if I re-saved the card with the "missing" Overlays they would show normally when loading the character on Studio Neo.

I managed to solve this problem by updating to OverlayMods_6.1.4.0, but I noticed one of 7 characters I edited actually lost one of her Overlays, I re added it and keep on doing some edits, and later on when I was about to make some adjustments and reloaded some of the edited chars I noticed that Material Editor slider edits now were not showing, and it was the same case as with the overlays in 6.1.3.0, they will seemingly not load(even tho they seemed to load correctly for a second on the loading freeze), if I saved the character with the "missing" edits they will show normally on Studio Neo, so the edist were there just not showing or showing as default on Char Creator.

![HoneySelect2 2024-06-12 12-27-29](https://github.com/ManlyMarco/Illusion-Overlay-Mods/assets/172578625/14cb565d-b6a7-4645-b61d-2b9f1b70a2bd)

![StudioNEOV2 2024-06-12 12-30-36](https://github.com/ManlyMarco/Illusion-Overlay-Mods/assets/172578625/4cac2f6b-cfff-4cab-8427-1650832afe4a)

Since I noticed it was all related to Overlay Mods, I tried going for an older version 6.1.2.0, and the issue is now gone and after doing some tests everything seems normal again, All this happened on a partially Vanilla(I added some plugins)  BetterRepack R8 that I had been using for a long time now.

**Comment by ManlyMarco** [comment]
@takahiro0327 Looks like another reload issue.

**Comment by takahiro0327** [comment]
@AsuraSeth 
What game are you playing?
I'll look into it, can you post here the cards that cause problems and the ones that don't?

@ManlyMarco 
Thanks for the mentions. Oh, God.

**Comment by ManlyMarco** [comment]
It's HoneySelect2 (or AIS since it's basically identical), but I'd guess that this could happen in KKS too?

**Comment by takahiro0327** [comment]
No, I tried using an overlay on clothes in KKS and it saves and loads fine.
He says he's 1 out of 7, so there must be some condition.

![image](https://github.com/ManlyMarco/Illusion-Overlay-Mods/assets/4230203/74fb3c31-51e5-477a-a453-e67efee14f59)

**Comment by AsuraSeth** [comment]
@takahiro0327 

it's in Honey Select 2(BetterRepack R8) Overlay Issue happened to me in version 6.1.3.0, then I realized a newer version was added and updated to 6.1.4.0, that fixed the overlay issue but now it was happening only on Material Editor Slider edits, texture edits were loaded but any sliders I modified in the ME were reseted to default, even when they looked as default if I didn't modified them they would actually save as they were and load correctly on Setudio Neo, so the Slider save data was there even tho it was showing as default, changined to version 6.1.2.0, and none of the mentioned problems were present, as I mentioned I don't know if I'm being clear, the issue seemed only visual in the character edit as on both cases overlay and ME edtis were still there just showing as default for some reason, even if I re-saved the card on the "default looking" state the edits would persist and show normally on SN, the only real loss of data was on one character that somehow loss one of her Overlays, but since I made all the edits myself I just put the texture back in.

**Comment by takahiro0327** [comment]
@AsuraSeth 
Use this. 6.1.2 equivalent DLL.
[HS2_OverlayMods.zip](https://github.com/user-attachments/files/15845027/HS2_OverlayMods.zip)
